### ISSUE TITLE
Sprint #1, MVP - brumGo

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-server-brumgo#5]
Create our new brumGo app using React-Native

- [x] The user will be greeted by a Loading Page with brumGo logo
- [x]  All users will see a map of the area  (Digbeth)
- [x] Points of interest marked on it
- [x] POI - will display a bit of trivia on a pop-up
